#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

echo "Symlink configuration"
mkdir -p config/sites/main
ln -snf ../../../.project/TYPO3/config.yaml config/sites/main/config.yaml
mkdir -p config/system
ln -snf ../../.project/TYPO3/settings.php config/system/settings.php

echo "Restart ddev (generates config/system/additional.php with database credentials)"
ddev restart

echo "Run 'composer install'"
ddev composer install

echo "Importing database"
ddev import-db --file=.project/data/db.sql.gz

echo "Copy .htaccess"
cp .build/vendor/typo3/cms-install/Resources/Private/FolderStructureTemplateFiles/root-htaccess .build/public/.htaccess

echo "Create fileadmin"
mkdir -p .build/public/fileadmin

echo "Flush caches"
ddev typo3 cache:flush

ddev describe
